// hotel.js

// ✅ Import images
import img1 from './img/13c6386862540c41822c39464b130b65.jpg';
import img2 from './img/Budget-hotel-in-udaipur.png';
import img3 from './img/expedia_group-2019366-9f5bf1-366307.jpg';
import img4 from './img/604167031.jpg';

// ✅ Hotel / Hostel / Budget Hotel Data
export const hotels = [
  {
    id: 'hostel-1',
    name: "Backpacker's Paradise Hostel",
    type: 'hostel',
    rating: 4.2,
    pricePerNight: 600,
    image: img1,
    amenities: ['Free WiFi', 'Common Kitchen', 'Lockers', 'AC', 'Laundry'],
    description: 'Perfect for budget travelers with shared dormitories and great social atmosphere',
    distance: '2.5 km from city center',
    studentFriendly: true,
    groupDiscounts: true,
    availability: 8,
    reviews: 324,
  },
  {
    id: 'hostel-2',
    name: 'Youth Hub Backpackers',
    type: 'hostel',
    rating: 4.4,
    pricePerNight: 750,
    image: img2,
    amenities: ['Free WiFi', 'Rooftop Cafe', 'Game Room', 'AC', 'Parking'],
    description: 'Modern hostel with private rooms and dormitories, popular among students',
    distance: '1.8 km from city center',
    studentFriendly: true,
    groupDiscounts: true,
    availability: 12,
    reviews: 567,
  },
  {
    id: 'budget-1',
    name: 'Student Inn Budget Hotel',
    type: 'budget_hotel',
    rating: 4.0,
    pricePerNight: 1200,
    image: img3,
    amenities: ['Free WiFi', 'Restaurant', 'AC', 'Hot Water', 'Room Service'],
    description: 'Clean and comfortable budget hotel with student-friendly rates',
    distance: '3.2 km from city center',
    studentFriendly: true,
    groupDiscounts: false,
    availability: 6,
    reviews: 289,
  },
  {
    id: 'budget-2',
    name: "Traveler's Rest Inn",
    type: 'budget_hotel',
    rating: 3.8,
    pricePerNight: 1000,
    image: img4,
    amenities: ['WiFi', 'Restaurant', 'AC', 'Parking'],
    description: 'Basic accommodation with essential amenities at affordable prices',
    distance: '4.1 km from city center',
    studentFriendly: true,
    groupDiscounts: true,
    availability: 4,
    reviews: 156,
  },
  {
    id: 'hotel-1',
    name: 'Heritage Grand Hotel',
    type: 'hotel',
    rating: 4.6,
    pricePerNight: 2500,
    image: img1,
    amenities: ['Free WiFi', 'Pool', 'Spa', 'Restaurant', 'Gym', 'Concierge'],
    description: 'Luxury hotel with premium amenities and excellent service',
    distance: '1.2 km from city center',
    studentFriendly: false,
    groupDiscounts: true,
    availability: 3,
    reviews: 892,
  },
  {
    id: 'hotel-2',
    name: 'City Center Boutique Hotel',
    type: 'hotel',
    rating: 4.3,
    pricePerNight: 1800,
    image: img2,
    amenities: ['Free WiFi', 'Restaurant', 'Bar', 'AC', 'Business Center'],
    description: 'Stylish boutique hotel in the heart of the city',
    distance: '0.8 km from city center',
    studentFriendly: false,
    groupDiscounts: false,
    availability: 5,
    reviews: 445,
  },
];
